### ISSUE TITLE
Something wrong when I try to build myserve

### ISSUE THREAD

**Issue by Xuanwo** [matpow2/cuwo#168]
Info of my serve:
Ubuntu 14.04, 2G memory, an with 2G swap set.

I get the wrong info:
```
root@i-sm3929oj:~/cuwo# python3.4 setup.py build_ext –inplace
Using SSE2 optimizations
Compiling ./terraingen/pydasm/pydasm.pyx because it changed.
Compiling ./cuwo/tgen.pyx because it changed.
Compiling ./cuwo/bytes.pyx because it changed.
Compiling ./cuwo/entity.pyx because it changed.
Cythonizing ./cuwo/bytes.pyx

Error compiling Cython file:
------------------------------------------------------------
...
        delete_write_stream(self.stream)

    cpdef bytes get(self):
        return get_stream_data(self.stream)

    cpdef bint write_vec3(self, value):
         ^
------------------------------------------------------------

cuwo/bytes.pyx:120:10: Signature not compatible with previous declaration

Error compiling Cython file:
------------------------------------------------------------
...
    cpdef inline bint write_double(self, double value):
        write_double(self.stream, value)
        return True

    @cython.final
    cpdef bint write_vec3(self, value) except *
                        ^
------------------------------------------------------------

cuwo/bytes.pxd:264:25: Previous declaration is here

Error compiling Cython file:
------------------------------------------------------------
...
        self.write_float(value.x)
        self.write_float(value.y)
        self.write_float(value.z)
        return True

    cpdef bint write_ivec3(self, value):
         ^
------------------------------------------------------------

cuwo/bytes.pyx:126:10: Signature not compatible with previous declaration

Error compiling Cython file:
------------------------------------------------------------
...

    @cython.final
    cpdef bint write_vec3(self, value) except *

    @cython.final
    cpdef bint write_ivec3(self, value) except *
                         ^
------------------------------------------------------------

cuwo/bytes.pxd:267:26: Previous declaration is here

Error compiling Cython file:
------------------------------------------------------------
...
        self.write_int32(value.x)
        self.write_int32(value.y)
        self.write_int32(value.z)
        return True

    cpdef bint write_qvec3(self, value):
         ^
------------------------------------------------------------

cuwo/bytes.pyx:132:10: Signature not compatible with previous declaration

Error compiling Cython file:
------------------------------------------------------------
...

    @cython.final
    cpdef bint write_ivec3(self, value) except *

    @cython.final
    cpdef bint write_qvec3(self, value) except *
                         ^
------------------------------------------------------------

cuwo/bytes.pxd:270:26: Previous declaration is here
Traceback (most recent call last):
  File "setup.py", line 235, in <module>
    ext_modules=cythonize(ext_modules),
  File "/usr/local/lib/python3.4/dist-packages/Cython/Build/Dependencies.py", line 865, in cythonize
    cythonize_one(*args[1:])
  File "/usr/local/lib/python3.4/dist-packages/Cython/Build/Dependencies.py", line 985, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: ./cuwo/bytes.pyx
```

**Comment by Sci-Tyx** [comment]
Run "pip install -I cython==0.21.2" and rebuild

**Comment by matpow2** [comment]
Ah, this is a recent regression in Cython. I will commit a fix soon, please stand by.

**Comment by Xuanwo** [comment]
Thanks @Sci-Tyx , its useful.
@matpow2 Thank you for your hard work~
