### ISSUE TITLE
ImportError: No module named 'cuwo.entity'

### ISSUE THREAD

**Issue by Sci-Tyx** [matpow2/cuwo#170]
After hours of trying to get this to work, I have had no luck.

I have reinstalled multiple times, redownloaded cuwo, reinstalled python, yet nothing has worked. I've had a conversation with a guy on the IRC and we had no luck either.

Traceback (most recent call last):
  File "/home/***/.pyenv/versions/3.4.1/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/***/.pyenv/versions/3.4.1/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/var/cubeworld/cuwo/cuwo/server.py", line 18, in <module>
    from cuwo import packet as packets
  File "/var/cubeworld/cuwo/cuwo/packet.py", line 24, in <module>
    from cuwo.entity import (EntityData, ItemData, read_masked_data,
ImportError: No module named 'cuwo.entity'

I am running Debian 3.2.63. I have tried method 1 & 2.

When I run bootstrap.sh I get
 destination path '.' already exists and is not an empty directory.

When I run "python setup.py build_ext --inplace" I get, "
Traceback (most recent call last):
  File "setup.py", line 235, in <module>
    ext_modules=cythonize(ext_modules),
  File "/home/***/.pyenv/versions/3.4.1/lib/python3.4/site-packages/Cython/Build/Dependencies.py", line 865, in cythonize
    cythonize_one(*args[1:])
  File "/home/***/.pyenv/versions/3.4.1/lib/python3.4/site-packages/Cython/Build/Dependencies.py", line 985, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: ./cuwo/bytes.pyx"

**Comment by Sci-Tyx** [comment]
SOLUTION: 

Run "pip install -I cython==0.21.2" to install the older version of Cython, then it works fine.
