### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by ziemerz** [matpow2/cuwo#180]
Hello

Whenever I run "sh run_server.sh" I get the following syntax errors:

run_server.sh: 6: run_server.sh: source: not found
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 151, in _run_module_as_main
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "/usr/lib/python2.7/runpy.py", line 113, in _get_module_details
    code = loader.get_code(mod_name)
  File "/usr/lib/python2.7/pkgutil.py", line 283, in get_code
    self.code = compile(source, self.filename, 'exec')
  File "/root/cuwo/cuwo/server.py", line 685
    def create_datagram_endpoint(self, *arg, port=0, **kw):
                                                ^
SyntaxError: invalid syntax

**Comment by TheReverend403** [comment]
Read the readme, cuwo requires Python 3.
