### ISSUE TITLE
Teleport command doesnt work

### ISSUE THREAD

**Issue by 00Freezy00** [matpow2/cuwo#182]
Player Freezy joined
Player hello joined
/teleport hello Freezy

Traceback (most recent call last):
  File "..\cuwo\script.py", line 355, in call_command
  File "..\cuwo\script.py", line 78, in **call**
  File "..\cuwo\script.py", line 154, in new_func
  File "E:\Server\scripts\commands.py", line 265, in teleport
    entity = script.connection.entity
AttributeError: 'ScriptInterface' object has no attribute 'entity'

**Comment by matpow2** [comment]
Is this still broken?

**Comment by matpow2** [comment]
Nope, it's fixed
