### ISSUE TITLE
Startin Server - Error

### ISSUE THREAD

**Issue by Misteralex007** [matpow2/cuwo#183]
Hi !

I installed the server via the bootstrap when it's finish, i changed the password for admin and time is coming to start the server but i got this error/message:

> run_server.sh: 6: run_server.sh: source: not found
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 151, in _run_module_as_main
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "/usr/lib/python2.7/runpy.py", line 113, in _get_module_details
    code = loader.get_code(mod_name)
  File "/usr/lib/python2.7/pkgutil.py", line 283, in get_code
    self.code = compile(source, self.filename, 'exec')
  File "/root/cuwo/cuwo/server.py", line 685
    def create_datagram_endpoint(self, *arg, port=0, **kw):
                                                                          ^
SyntaxError: invalid syntax

So do you have the same problem ? And how to fix it ?

Thanks,
Regards,

Misteralex007

**Comment by TheReverend403** [comment]
You're using Python 2.7 while cuwo requires Python 3.3 or newer.

**Comment by Misteralex007** [comment]
Ok thanks, but it still doesn't work. I'm using python3.5.
(I have several python version installed on my VPS.)

> root@aboutgeek:~/cuwo-master# sh run_server.sh
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/cuwo-master/cuwo/server.py", line 736, in <module>
    main()
  File "/root/cuwo-master/cuwo/server.py", line 721, in main
    server = CubeWorldServer(loop, config)
  File "/root/cuwo-master/cuwo/server.py", line 473, in __init__
    base.use_entities)
  File "/root/cuwo-master/cuwo/server.py", line 111, in __init__
    super().__init__(*arg, **kw)
  File "/root/cuwo-master/cuwo/world.py", line 240, in __init__
    raise FileNotFoundError('Missing asset file %r' % path)
FileNotFoundError: Missing asset file '/root/cuwo-master/data/data1.db'

So now it seems like some files are missing ?
(build's log -> http://pastebin.com/DBaBvcAV)

Thanks,

Misteralex007,

**Comment by Faulik** [comment]
>> https://github.com/matpow2/cuwo/blob/master/data/README.txt
