### ISSUE TITLE
i can't run the server in windows

### ISSUE THREAD

**Issue by DVD-DY** [matpow2/cuwo#193]
hi i have windows 10, 64 bits and I try to open run.bat and it gives me this error

Traceback (most recent call last):
  File "C:\Python36-x64\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
  File "C:\Python36-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
  File "../cuwo/server.py", line 18, in <module>
  File "..\cuwo\packet.py", line 24, in <module>
  File "__init__.pxd", line 155, in init cuwo.tgen_wrap
  File "C:\Python36-x64\lib\site-packages\numpy\__init__.py", line 142, in <module>
  File "C:\Python36-x64\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
  File "C:\Python36-x64\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
  File "C:\Python36-x64\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
  File "C:\Python36-x64\lib\site-packages\numpy\core\__init__.py", line 38, in <module>
  File "C:\Python36-x64\lib\site-packages\numpy\core\numeric.py", line 1820, in <module>
  File "C:\Python36-x64\lib\site-packages\numpy\core\arrayprint.py", line 35, in <module>
  File "C:\Python36-x64\lib\site-packages\numpy\core\fromnumeric.py", line 15, in <module>
ImportError: cannot import name '_methods'

what i can do? thanks

**Comment by matpow2** [comment]
Fixed in latest binaries
