### ISSUE TITLE
Server crash and lagg

### ISSUE THREAD

**Issue by megaherox** [matpow2/cuwo#194]
We play 10 minutes and then the server crashes log:
[2017-07-27 22:04:26,790] Exception in callback LoopingCall.schedule(0.02, True)
handle: <TimerHandle when=221847.274233015 LoopingCall.schedule(0.02, True)>
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/asyncio/events.py", line 127, in _run
    self._callback(*self._args)
  File "/var/games/cubeworld/cuwo/loop.py", line 45, in schedule
    self.func(*self.arg, **self.kw)
  File "/var/games/cubeworld/cuwo/server.py", line 589, in update
    out_packets = self.world.update(self.update_loop.dt)
  File "/var/games/cubeworld/cuwo/world.py", line 415, in update
    raise NotImplementedError()
NotImplementedError

**Comment by matpow2** [comment]
This is a known issue, and it's being worked on. Thanks for reporting it!

**Comment by megaherox** [comment]
mhn the problem the issue comes every time .. so we cant play .
thanks for the answer. Is there any fix ?

**Comment by matpow2** [comment]
For now, you can disable tgen in `base.py`. I'll be looking into the issue tomorrow, so it won't be long now :)

**Comment by megaherox** [comment]
ok thanks (:

**Comment by megaherox** [comment]
when i disable tgen and start the server it crashes instantly :D

**Comment by matpow2** [comment]
Fixed in trunk.
