### ISSUE TITLE
Teleport command is broken

### ISSUE THREAD

**Issue by SinusStudios** [matpow2/cuwo#199]
When logging in and entering `/teleport waffeln otto` (valid player names, online)
Output in console:
`Traceback (most recent call last):
  File "/home/user/cuwo/cuwo/script.py", line 361, in call_command
    ret = command(user, *args) or ''
  File "/home/user/cuwo/cuwo/script.py", line 82, in __call__
    return self.func(*arg, **kw)
  File "/home/user/cuwo/cuwo/script.py", line 158, in new_func
    return func(script, *arg, **kw)
  File "/home/user/cuwo/scripts/commands.py", line 284, in teleport
    pos = qvec3(int(a), int(b), 0) * constants.CHUNK_SCALE
ValueError: invalid literal for int() with base 10: 'waffeln'`
System: Debian Linux 8, x64 (VPS)

**Comment by matpow2** [comment]
/teleport does not allow you to teleport someone else, only yourself, but this could probably be added.

**Comment by SinusStudios** [comment]
I tried to teleport myself (waffeln) to the player "otto".
