### ISSUE TITLE
Running CUWO for the first time (linux)

### ISSUE THREAD

**Issue by nataklug** [matpow2/cuwo#203]
Hello!

I am trying to install CUWO in an Ubuntu server. The problem is I don't have the database files and it's not working:

```
nataniel@NatanielTeste:~/cuwo$ sh run_server.sh
Picroma login (leave empty to skip package)
Email:
Traceback (most recent call last):
  File "/home/nataniel/.pyenv/versions/3.6.1/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/nataniel/.pyenv/versions/3.6.1/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/nataniel/cuwo/cuwo/server.py", line 915, in <module>
    main()
  File "/home/nataniel/cuwo/cuwo/server.py", line 900, in main
    server = CubeWorldServer(loop, config)
  File "/home/nataniel/cuwo/cuwo/server.py", line 544, in __init__
    chunk_retire_time=base.chunk_retire_time)
  File "/home/nataniel/cuwo/cuwo/server.py", line 122, in __init__
    super().__init__(*arg, **kw)
  File "/home/nataniel/cuwo/cuwo/world.py", line 338, in __init__
    raise FileNotFoundError('Missing asset file %r' % path)
FileNotFoundError: Missing asset file '/home/nataniel/cuwo/data/data1.db'
```

What can I do to solve it?

**Comment by matpow2** [comment]
Get the database files somehow and put them in the `data` folder. Can't help you with that, sorry.

**Comment by nataklug** [comment]
Thanks!
