### ISSUE TITLE
I dont get it

### ISSUE THREAD

**Issue by henrik9999** [matpow2/cuwo#209]
Using SSE2 optimizations
Compiling ./cuwo/tgen.pyx because it changed.
Compiling ./cuwo/bytes.pyx because it changed.
Compiling ./cuwo/entity.pyx because it changed.
Compiling ./cuwo/tgen_wrap.pyx because it changed.
[1/4] Cythonizing ./cuwo/bytes.pyx
[2/4] Cythonizing ./cuwo/entity.pyx
[3/4] Cythonizing ./cuwo/tgen.pyx
[4/4] Cythonizing ./cuwo/tgen_wrap.pyx
Traceback (most recent call last):
  File "setup.py", line 130, in <module>
    ext_modules=cythonize(ext_modules),
  File "/home/cuwo/.pyenv/versions/3.6.1/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1026, in cythonize
    cythonize_one(*args)
  File "/home/cuwo/.pyenv/versions/3.6.1/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1129, in cythonize_one
    result = compile_single(pyx_file, options, full_module_name=full_module_name)
  File "/home/cuwo/.pyenv/versions/3.6.1/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 649, in compile_single
    return run_pipeline(source, options, full_module_name)
  File "/home/cuwo/.pyenv/versions/3.6.1/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 499, in run_pipeline
    err, enddata = Pipeline.run_pipeline(pipeline, source)
  File "/home/cuwo/.pyenv/versions/3.6.1/lib/python3.6/site-packages/Cython/Compiler/Pipeline.py", line 354, in run_pipeline
    data = run(phase, data)
  File "/home/cuwo/.pyenv/versions/3.6.1/lib/python3.6/site-packages/Cython/Compiler/Pipeline.py", line 334, in run
    return phase(data)
  File "/home/cuwo/.pyenv/versions/3.6.1/lib/python3.6/site-packages/Cython/Compiler/Pipeline.py", line 52, in generate_pyx_code_stage
    module_node.process_implementation(options, result)
  File "/home/cuwo/.pyenv/versions/3.6.1/lib/python3.6/site-packages/Cython/Compiler/ModuleNode.py", line 142, in process_implementation
    self.generate_c_code(env, options, result)
  File "/home/cuwo/.pyenv/versions/3.6.1/lib/python3.6/site-packages/Cython/Compiler/ModuleNode.py", line 378, in generate_c_code
    self.body.generate_function_definitions(env, code)
  File "/home/cuwo/.pyenv/versions/3.6.1/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 438, in generate_function_definitions
    stat.generate_function_definitions(env, code)
  File "/home/cuwo/.pyenv/versions/3.6.1/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 438, in generate_function_definitions
    stat.generate_function_definitions(env, code)
  File "/home/cuwo/.pyenv/versions/3.6.1/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 4773, in generate_function_definitions
    self.body.generate_function_definitions(self.scope, code)
  File "/home/cuwo/.pyenv/versions/3.6.1/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 438, in generate_function_definitions
    stat.generate_function_definitions(env, code)
  File "/home/cuwo/.pyenv/versions/3.6.1/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 4971, in generate_function_definitions
    self.body.generate_function_definitions(env, code)
  File "/home/cuwo/.pyenv/versions/3.6.1/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 438, in generate_function_definitions
    stat.generate_function_definitions(env, code)
  File "/home/cuwo/.pyenv/versions/3.6.1/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 3163, in generate_function_definitions
    FuncDefNode.generate_function_definitions(self, env, code)
  File "/home/cuwo/.pyenv/versions/3.6.1/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 1976, in generate_function_definitions
    self.generate_function_body(env, code)
  File "/home/cuwo/.pyenv/versions/3.6.1/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 1738, in generate_function_body
    self.body.generate_execution_code(code)
  File "/home/cuwo/.pyenv/versions/3.6.1/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 444, in generate_execution_code
    stat.generate_execution_code(code)
  File "/home/cuwo/.pyenv/versions/3.6.1/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 5102, in generate_execution_code
    self.generate_rhs_evaluation_code(code)
  File "/home/cuwo/.pyenv/versions/3.6.1/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 5389, in generate_rhs_evaluation_code
    self.rhs.generate_evaluation_code(code)
  File "/home/cuwo/.pyenv/versions/3.6.1/lib/python3.6/site-packages/Cython/Compiler/ExprNodes.py", line 720, in generate_evaluation_code
    self.generate_result_code(code)
  File "/home/cuwo/.pyenv/versions/3.6.1/lib/python3.6/site-packages/Cython/Compiler/ExprNodes.py", line 13138, in generate_result_code
    self.arg.py_result(), self.result(), self.pos, code, from_py_function=from_py_function))
  File "/home/cuwo/.pyenv/versions/3.6.1/lib/python3.6/site-packages/Cython/Compiler/PyrexTypes.py", line 514, in from_py_call_code
    error_condition or self.error_condition(result_code)
  File "/home/cuwo/.pyenv/versions/3.6.1/lib/python3.6/site-packages/Cython/Compiler/PyrexTypes.py", line 2483, in from_py_call_code
    assert not error_condition, '%s: %s' % (error_pos, error_condition)
AssertionError: (<FileSourceDescriptor:/home/cuwo/cuwo3/cuwo/tgen_wrap.pyx>, 350, 29): PyErr_Occurred()
cuwo@srv49641:~/cuwo3$ sh run_server.sh
Traceback (most recent call last):
  File "/home/cuwo/.pyenv/versions/3.6.1/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/cuwo/.pyenv/versions/3.6.1/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/cuwo/cuwo3/cuwo/server.py", line 18, in <module>
    from cuwo import packet as packets
  File "/home/cuwo/cuwo3/cuwo/packet.py", line 24, in <module>
    from cuwo.tgen_wrap import (WrapEntityData as EntityData,
ModuleNotFoundError: No module named 'cuwo.tgen_wrap'
cuwo@srv49641:~/cuwo3$ sh run_server.sh
Traceback (most recent call last):
  File "/home/cuwo/.pyenv/versions/3.6.1/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/cuwo/.pyenv/versions/3.6.1/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/cuwo/cuwo3/cuwo/server.py", line 18, in <module>
    from cuwo import packet as packets
  File "/home/cuwo/cuwo3/cuwo/packet.py", line 24, in <module>
    from cuwo.tgen_wrap import (WrapEntityData as EntityData,
ModuleNotFoundError: No module named 'cuwo.tgen_wrap'

**Comment by Dynrothe** [comment]
Did any of you ever figure this out?

**Comment by henrik9999** [comment]
nope

**Comment by matpow2** [comment]
Fixed in trunk
