### ISSUE TITLE
Can´t Start Server [Windows 10]

### ISSUE THREAD

**Issue by ReflexShot** [matpow2/cuwo#213]
I have installed from the quickstart guide but when i try to run the run.bat file i get this error PLS help.
I skipped picoroma login  because i dont have a picoroma account.

Picroma login (leave empty to skip package)
Email:
Traceback (most recent call last):
  File "C:\Python36-x64\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
  File "C:\Python36-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
  File "../cuwo/server.py", line 915, in <module>
  File "../cuwo/server.py", line 900, in main
  File "../cuwo/server.py", line 544, in __init__
  File "../cuwo/server.py", line 122, in __init__
  File "..\cuwo\world.py", line 338, in __init__
FileNotFoundError: Missing asset file 'C:\\Users\\garib\\Desktop\\dist\\data\\data1.db'

C:\Users\garib\Desktop\dist>pause

**Comment by henrik9999** [comment]
you need to login for cuwo to download the server files or else you could move **data1.db** **data4.db** and **server.exe** from the cubeworld directory to the data folder from the server
