### ISSUE TITLE
Build on linux, error with tgen_wrap.pyx

### ISSUE THREAD

**Issue by flifloo** [matpow2/cuwo#214]
I'm on Debian 9 with Python3.6 on a VPS.
I try to build with a git clone and I get this error :

`root@ftw-vps:/opt/cuwo# python3.6 setup.py build_ext --inplace
Using SSE2 optimizations
Compiling ./cuwo/tgen.pyx because it changed.
Compiling ./cuwo/bytes.pyx because it changed.
Compiling ./cuwo/entity.pyx because it changed.
Compiling ./cuwo/tgen_wrap.pyx because it changed.
[1/4] Cythonizing ./cuwo/bytes.pyx
[2/4] Cythonizing ./cuwo/entity.pyx
[3/4] Cythonizing ./cuwo/tgen.pyx
[4/4] Cythonizing ./cuwo/tgen_wrap.pyx
Traceback (most recent call last):
  File "setup.py", line 130, in <module>
    ext_modules=cythonize(ext_modules),
  File "/usr/local/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1026, in cythonize
    cythonize_one(*args)
  File "/usr/local/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1129, in cythonize_one
    result = compile_single(pyx_file, options, full_module_name=full_module_name)
  File "/usr/local/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 649, in compile_single
    return run_pipeline(source, options, full_module_name)
  File "/usr/local/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 499, in run_pipeline
    err, enddata = Pipeline.run_pipeline(pipeline, source)
  File "/usr/local/lib/python3.6/site-packages/Cython/Compiler/Pipeline.py", line 354, in run_pipeline
    data = run(phase, data)
  File "/usr/local/lib/python3.6/site-packages/Cython/Compiler/Pipeline.py", line 334, in run
    return phase(data)
  File "/usr/local/lib/python3.6/site-packages/Cython/Compiler/Pipeline.py", line 52, in generate_pyx_code_stage
    module_node.process_implementation(options, result)
  File "/usr/local/lib/python3.6/site-packages/Cython/Compiler/ModuleNode.py", line 142, in process_implementation
    self.generate_c_code(env, options, result)
  File "/usr/local/lib/python3.6/site-packages/Cython/Compiler/ModuleNode.py", line 378, in generate_c_code
    self.body.generate_function_definitions(env, code)
  File "/usr/local/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 438, in generate_function_definitions
    stat.generate_function_definitions(env, code)
  File "/usr/local/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 438, in generate_function_definitions
    stat.generate_function_definitions(env, code)
  File "/usr/local/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 4773, in generate_function_definitions
    self.body.generate_function_definitions(self.scope, code)
  File "/usr/local/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 438, in generate_function_definitions
    stat.generate_function_definitions(env, code)
  File "/usr/local/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 4971, in generate_function_definitions
    self.body.generate_function_definitions(env, code)
  File "/usr/local/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 438, in generate_function_definitions
    stat.generate_function_definitions(env, code)
  File "/usr/local/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 3163, in generate_function_definitions
    FuncDefNode.generate_function_definitions(self, env, code)
  File "/usr/local/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 1976, in generate_function_definitions
    self.generate_function_body(env, code)
  File "/usr/local/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 1738, in generate_function_body
    self.body.generate_execution_code(code)
  File "/usr/local/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 444, in generate_execution_code
    stat.generate_execution_code(code)
  File "/usr/local/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 5102, in generate_execution_code
    self.generate_rhs_evaluation_code(code)
  File "/usr/local/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 5389, in generate_rhs_evaluation_code
    self.rhs.generate_evaluation_code(code)
  File "/usr/local/lib/python3.6/site-packages/Cython/Compiler/ExprNodes.py", line 720, in generate_evaluation_code
    self.generate_result_code(code)
  File "/usr/local/lib/python3.6/site-packages/Cython/Compiler/ExprNodes.py", line 13138, in generate_result_code
    self.arg.py_result(), self.result(), self.pos, code, from_py_function=from_py_function))
  File "/usr/local/lib/python3.6/site-packages/Cython/Compiler/PyrexTypes.py", line 514, in from_py_call_code
    error_condition or self.error_condition(result_code)
  File "/usr/local/lib/python3.6/site-packages/Cython/Compiler/PyrexTypes.py", line 2483, in from_py_call_code
    assert not error_condition, '%s: %s' % (error_pos, error_condition)
AssertionError: (<FileSourceDescriptor:/opt/cuwo/cuwo/tgen_wrap.pyx>, 350, 29): PyErr_Occurred()`

Someone can help me ?

**Comment by BeTheWind42** [comment]
This a bug caused by the last version of Cython, install an older version:
`pip3 install Cython==0.24 `

**Comment by flifloo** [comment]
Thanks !

**Comment by Dynrothe** [comment]
That didn't work for me :(
