### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by Vankovas** [matpow2/cuwo#215]
Hello,
I have installed Python, set it up, installed cythion and this is what happens when i try to run build.bat and run_server.bat (also i have copied the files to the directory).

C:\Users\Vankovas\Desktop\cuwo-master>build.bat

C:\Users\Vankovas\Desktop\cuwo-master>C:\Windows\py.exe -3 setup.py build_ext --inplace
Traceback (most recent call last):
  File "setup.py", line 21, in <module>
    import numpy
ImportError: No module named 'numpy'

C:\Users\Vankovas\Desktop\cuwo-master>run_server.bat

C:\Users\Vankovas\Desktop\cuwo-master>C:\Windows\py.exe -3 -m cuwo.server
Traceback (most recent call last):
  File "C:\Python34\lib\runpy.py", line 151, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name)
  File "C:\Python34\lib\runpy.py", line 126, in _get_module_details
    code = loader.get_code(mod_name)
  File "<frozen importlib._bootstrap>", line 1572, in get_code
  File "<frozen importlib._bootstrap>", line 1532, in source_to_code
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "C:\Users\Vankovas\Desktop\cuwo-master\cuwo\server.py", line 805
    path = os.path.join(self.config.base.save_path, f'{name}.dat')
                                                                ^
SyntaxError: invalid syntax

C:\Users\Vankovas\Desktop\cuwo-master>pause
Press any key to continue . . .

**Comment by matpow2** [comment]
1) You need numpy installed.
2) I would advise you to use Python 3.6.

**Comment by Vankovas** [comment]
Hi, I installed numpy trough pip but now it gives me this

C:\WINDOWS\system32>C:\Windows\py.exe -3 -m cuwo.server
C:\Python34\python.exe: Error while finding spec for 'cuwo.server' (<class 'ImportError'>: No module named 'cuwo')

**Comment by Vankovas** [comment]
And this is what it gives me when i dont run it as an administrator-
  File "C:\Python34\lib\runpy.py", line 151, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name)
  File "C:\Python34\lib\runpy.py", line 126, in _get_module_details
    code = loader.get_code(mod_name)
  File "<frozen importlib._bootstrap>", line 1572, in get_code
  File "<frozen importlib._bootstrap>", line 1532, in source_to_code
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "C:\Users\Vankovas\Desktop\cuwo-master\cuwo\server.py", line 805
    path = os.path.join(self.config.base.save_path, f'{name}.dat')

I tried with pip to download 'runpy' but it couldnt
