### ISSUE TITLE
Please help :)

### ISSUE THREAD

**Issue by Vankovas** [matpow2/cuwo#216]
-Intalled python 3.6.5
-Installed cythion
-Installed numpy
-Installed irc3
-Installed pyrr
To build cuwo, run `python setup.py build_ext --inplace`. -- did this too

And when i go and run the run_server.bat it gives me this, some problem with runpy

C:\Users\Vankovas\Desktop\cuwo-master>C:\Windows\py.exe -3 -m cuwo.server
Traceback (most recent call last):
  File "C:\Users\Vankovas\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Vankovas\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Vankovas\Desktop\cuwo-master\cuwo\server.py", line 18, in <module>
    from cuwo import packet as packets
  File "C:\Users\Vankovas\Desktop\cuwo-master\cuwo\packet.py", line 24, in <module>
    from cuwo.tgen_wrap import (WrapEntityData as EntityData,
ModuleNotFoundError: No module named 'cuwo.tgen_wrap'

**Comment by matpow2** [comment]
Sounds like your `setup.py` build did not complete properly. What did the build step give you?

**Comment by P3nguin33** [comment]
Probably no use to you now but for anyone with the same problem, this may help. In the data folder, you need data1.db, data4.db and server.exe (all of which are from the original game files).
