### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 46: invalid start byte

### ISSUE THREAD

**Issue by Adenser** [matpow2/cuwo#230]
root@:~/cuwo# sh run_server.sh
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/cuwo/cuwo/server.py", line 954, in <module>
    main()
  File "/root/cuwo/cuwo/server.py", line 935, in main
    if config.base.use_tgen:
  File "/root/cuwo/cuwo/config.py", line 56, in __getattr__
    self.load(name)
  File "/root/cuwo/cuwo/config.py", line 41, in load
    data = fp.read()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 46: invalid start byte

**Comment by Adenser** [comment]
nvm I fixed it
do no edit ANYTHING that is inside ./config without using editor like nano. It will broke everything.
